apiVersion: v1
kind: Service
metadata:
  name: {{ include "to-do-list.fullname" . }}
  labels:
    {{- include "to-do-list.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
  selector:
    {{- include "to-do-list.selectorLabels" . | nindent 4 }}
