apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc-local
spec:
  resources:
    requests:
      storage: {{ .Values.volumeclaim.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
    
