apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv-local
  labels:
    type: local-storage
spec:
  capacity:
    storage: {{ .Values.volume.storage }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.volume.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.volume.reclaimPolicy }}
  storageClassName: local-storage
  local:
    path: {{ .Values.volume.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - node
    
